CREATE DATABASE ex4;
USE ex4;

CREATE TABLE cliente (
	cpf VARCHAR(15) NOT NULL PRIMARY KEY,
    nome VARCHAR(70) NOT NULL,
    dtNasc DATE DEFAULT NULL
    )ENGINE = InnoDB DEFAULT CHARSET = latin1;

