USE ex4;

CREATE TABLE patio (
	num INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ender VARCHAR(50) DEFAULT NULL,
    capacidade INT DEFAULT NULL
    ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;