USE ex4;

CREATE TABLE tanque (
	id_tanque INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipo VARCHAR(200) NOT NULL,
    capacidade INT DEFAULT 10000,
    quantidade INT DEFAULT 0
    ) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;